#!/usr/bin/env bash

set -euo pipefail
loc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
pushd ${loc}

go build
docker build --tag=ginvalid .

# copy init server data to live location
srvdata="/tmp/gin-valid-data-${RANDOM}"
cp -a "./srvdata/." "${srvdata}"

configdir="${srvdata}/config"
configfile="${configdir}/cfg.json"

docker run --rm --network=ginbridge -v ${srvdata}:/gin-valid -v ${configdir}:/config/ -p 3033:3033 --name ginvalid -it ginvalid
